#!/bin/bash

UNDERVIEW_BUILD_OUTPUT_DIR="$(pwd)/working/build_output"
export PKG_CONFIG_PATH="${UNDERVIEW_BUILD_OUTPUT_DIR}/lib/pkgconfig:${PKG_CONFIG_PATH}"
export LIBGL_DRIVERS_PATH="${UNDERVIEW_BUILD_OUTPUT_DIR}/lib/dri"
export PATH="${UNDERVIEW_BUILD_OUTPUT_DIR}/bin:${PATH}"
export LD_LIBRARY_PATH="${UNDERVIEW_BUILD_OUTPUT_DIR}/lib:${LD_LIBRARY_PATH}"
